### ISSUE TITLE
No such file or directory error...

### ISSUE THREAD

**Issue by objectkit** [smiclea/brackets-js-concat#3]
First time trying brackets-js-concat. I have a file called test.js in the project directory root. This is my config:

```
// @see https://github.com/smiclea/brackets-js-concat
// whether to concat all files when one is saved, or not
concatOnSave = false;

// path to the output file composed of the concatenated files
output = build/build.js;

// whether to minify the output file or not
minify = true;

// the list of files (paths relative to project root) to concatenate
// path is relative to project root
-test.js
```

The file _test.js_ exists. After running js-concat, even if there is an error, it does write a file the _build.js_ in the correct place, though empty. When attempting to concatenate files, either by having concatOnSave enabled and saving files, or having it set to false and trying to concatenate by right clicking on the js.concat file, I get the following errors 

```
[brackets-js-concat] uglify-js error: /bin/sh: /Users/USER/Library/Application: No such file or directory
main.js
file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/brackets-js-concat/main.js at line: 219, column: 16
at Console.console.error (file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/malas34.brackets-console-plus/main.js:436:41)
at NodeConnection.<anonymous> (file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/brackets-js-concat/main.js:219:16)
at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)
at NodeConnection._receive (/utils/NodeConnection.js:498:34)
```

On occasion I also see this error in console:

```
[brackets-js-concat] uglify-js error: /bin/sh: /Users/USER/Library/Application: No such file or directory
main.js
file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/brackets-js-concat/main.js at line: 219, column: 16
at Console.console.error (file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/malas34.brackets-console-plus/main.js:436:41)
at NodeConnection.<anonymous> (file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/brackets-js-concat/main.js:219:16)
at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)
at NodeConnection._receive (/utils/NodeConnection.js:498:34)
[brackets-js-concat] Error reading file for concatenation (undefined): NotFound
main.js
file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/brackets-js-concat/main.js at line: 154, column: 13
at Console.console.error (file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/malas34.brackets-console-plus/main.js:436:41)
at file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/brackets-js-concat/main.js:154:13
at File.eval (/filesystem/File.js:112:17)
at eval (/filesystem/impls/appshell/AppshellFileSystem.js:389:21)
at eval (/filesystem/impls/appshell/AppshellFileSystem.js:232:17)
```

Any suggestions? Do I have to install uglify-js via NPM? I did try this on the long shot, but it made no difference, assumably because Brackets has its own node dependency structure somewhere.... Is it a path issue lurking somewhere? I'm using OS X as you can probably tell from the console output above.

Thanks!

**Comment by smiclea** [comment]
Hi! You seem to be missing a semi-colon. The path to the file should be:
-test.js;

Let me know if this solves your problem!

**Comment by objectkit** [comment]
Hey smiclea - thanks for getting back to me! Really appreciate it! Nope- sorry that was a typo in the post- the path was typed correctly as 

```
-test.js;
```

I also tried creating a new project. What was weird here was that all files were indeed concatenated (great), but there was no minification!

I get this error:

```
[brackets-js-concat] uglify-js error: /bin/sh: /Users/USER/Library/Application: No such file or directory
main.js
file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/brackets-js-concat/main.js at line: 219, column: 16
at Console.console.error (file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/malas34.brackets-console-plus/main.js:436:41)
at NodeConnection.<anonymous> (file:///Users/USER/Library/Application%20Support/Brackets/extensions/user/brackets-js-concat/main.js:219:16)
at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)
at NodeConnection._receive (/utils/NodeConnection.js:498:34)
```

From afar, it looks like a path issue with uglify... but I really dont know. Any other suggestions?

_UPDATE_: concatenation works fine with _minify = false;_. When _minify = true_, an empty build file is created and the error is output to console.
